name: publish_npm_package

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DEPLOY_DIR: examples/vite/dist
  DEPLOY_FILTER: example-swetrix-vue-vite

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          VITE_SWETRIX_PROJECT_ID: ${{ secrets.VITE_SWETRIX_PROJECT_ID }}
        uses: ghacts/static-site@main
        with:
          node-version: 18
          skip-lint: true
          skip-test: true
          build-script: 'build:example'
          output-dir: ${{ env.DEPLOY_DIR }}

      - name: Set publish tag
        run: |
          ([[ "${GITHUB_REF#refs/*/v}" =~ ^([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+)$ ]] && echo "PUBLISH_TAG=latest" >> "${GITHUB_ENV}") || echo "PUBLISH_TAG=rc" >> "${GITHUB_ENV}"

      - name: Deploy example
        env:
          PROD: ${{ env.PUBLISH_TAG == 'latest' }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        uses: ghacts/manual-deploy-to-netlify@main
        with:
          auth-token: ${{ env.NETLIFY_AUTH_TOKEN }}
          site: ${{ env.NETLIFY_SITE_ID }}
          filter: ${{ env.DEPLOY_FILTER }}
          prod: ${{ env.PROD }}

      - name: Publish NPM package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${{ env.NPM_TOKEN }}"
          pnpm publish --access public --tag ${{ env.PUBLISH_TAG }}
